### ISSUE TITLE
Font is not working properly

### ISSUE THREAD

**Issue by TheSETJ** [sgolovine/PlexNerdfont#2]
I use babun as my shell and zsh as my terminal. Glyphs only work for normal weight and not for light, extra-light and etc. Also, font does not work in Visual Studio Code's terminal (which is zsh again) at all.

![image](https://user-images.githubusercontent.com/10893088/38374777-c9ba17f6-3909-11e8-938e-9337a2a7713b.png)
(IBMPlexMono Nerd Font Mono Medium is set for babun and IBMPlexMono Nerd Font Mono is set for VS Code's terminal)

**Comment by sgolovine** [comment]
I just updated the font's, adding a 'windows-compatable' folder. Those should work.
